language: clojure

addons:
  apt:
    packages:
    - jackd
    - jack-tools
    - ant
    - openjdk-6-jdk
    - fftw3
env:
  - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket

before_script:
  - sudo jackd -r -d dummy -r 44100 &
  - sleep 10s
